version: '3.8'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
    ports:
      - 33306:3306
    volumes:
      - "mariadb_data:/bitnami/mariadb"
  phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - mariadb
  myapp:
    image: myapp
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
    command: >
      sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
    volumes:
      - "./project:/app"
    depends_on:
      - mariadb
      - phpmyadmin
volumes:
  mariadb_data:
    driver: local